# Gopkg.toml example

[prune]
  go-tests = true
  unused-packages = true

[[override]]
  name = "github.com/asecurityteam/settings"
  version = "^0.1.0"

[[constraint]]
  name = "github.com/rs/xstats"
  branch = "master"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  name = "github.com/golang/mock"
  version = "1.3.1"
